pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim' 
            args '-p 3400:3400' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'npm install' 
            }
        }
    }
}
